### ISSUE TITLE
Add Odyssey warps

### ISSUE THREAD

**Issue by wbnightwolf** [AkadenTK/superwarp#14]
Any chance this could work in incursion or odyssey?

**Comment by AkadenTK** [comment]
Yes, there's a chance. But a slim one. These would be low on the priority list.

**Comment by anthem127** [comment]
Would pay for you to work on this seriously.  Point me in the direction of PayPal and I’ll dump $100 for you just to attempt it.  Desperately need this for my 6box setup for Odyssey

**Comment by ianandersonlol** [comment]
NPCinteract or interactbruh will do that for you.

**Comment by Viresy** [comment]
With odyssey being the hot new content, getting some functionality added would be amazing.

**Comment by AkadenTK** [comment]
Odyssey has been added as of 1.0.

Please submit a second feature request for Incursion, if it is still desired :)
