### ISSUE TITLE
Broken by most recent update

### ISSUE THREAD

**Issue by Terico1989** [AkadenTK/superwarp#15]
This seems broken by the most recent update in the sense that a character cannot warp to a zone they do not have. Unsure if this is addon related or game related right now.

**Comment by Aerec** [comment]
Can confirm this, no warps seem to work for zones the character does not have access to.

**Comment by sasaan** [comment]
To add on to this, I can warp to new waypoints in adoulin if I am at another waypoint in that zone, but only then.

**Comment by AkadenTK** [comment]
Alas, after testing it seems like it's a check on SE's servers. Not using Superwarp, I was able to show the locations I haven't unlocked yet to choose them through the in-game UI, and it broke there too. 
Superwarp is no longer able to take you to places you haven't unlocked yet, so I've removed the option to prevent confusion (and sending bad packets to the server).

**Comment by Terico1989** [comment]
Thanks for the update, dunno if it's a coincidence, since I started using the new version, I seem to be getting dc'd a lot when using the addon now, whereas before there were no issues?

**Comment by AkadenTK** [comment]
I think it must be unrelated as I used it all day yesterday with no crashes/dcs.
