### ISSUE TITLE
VW warp not working

### ISSUE THREAD

**Issue by Latravant** [AkadenTK/superwarp#21]
i'm trying to vw to rolanberry fields, which is unlocked, but it says warning cannot teleport from here. canceling action. 
i'm standing right next to the npc in present day bastok. i reloaded the addon as well.

**Comment by RubenatorX** [comment]
change line 16 of `supwerwarp\map\voidwatch.lua` to
`if past_warp_zones:contains(zone) ~= (destination.shadowreign or false) then`

**Comment by AkadenTK** [comment]
Should be fixed according to one tester on the windower discord. Version bumped to 0.97.4
