### ISSUE TITLE
Survival Guide not working

### ISSUE THREAD

**Issue by bumpouz** [AkadenTK/superwarp#41]
Tries to use survival guide, 
"Warping via Survival Guide to location. Timed out waiting for response from menu. Retrying..."
will just repeat that till you stop it.

**Comment by AkadenTK** [comment]
I need more information like what command you used, how close are you to the survival guide, are you interacting with another npc, etc.

**Comment by bumpouz** [comment]
I'm standing right in front of a Survival Guide using //sg all Northern San d'Oria or any location name. Also tried just //sg Northern San d'Oria with the same result. It does this no matter where I put the location. NS is just the one I attached the screenshot from. Not interacting with any other npcs or hp. It targets the sg then does nothing and tries again.  I am on a private server if that makes a difference, but //hp all Northern San d"Oria or any location works 
![img_20230710_18405](https://github.com/AkadenTK/superwarp/assets/57812808/6117a938-9d6e-4111-979e-50209f56d9a6)

**Comment by bumpouz** [comment]
I turned the debug on. Here is the screenshot of what it is seeing
![img_20230723_1107323](https://github.com/AkadenTK/superwarp/assets/57812808/35cd5d68-6132-4480-a095-c9cda5684c6b)
