### ISSUE TITLE
Two Questions

### ISSUE THREAD

**Issue by Mercurian** [AkadenTK/superwarp#42]
1, I literally cannot figure out how the fuck to use the command. What Exactly do I type. Say Tavnazia hp1

2, I saved the original v.095 Can I still warp anywhere I don't have, I don't care if it's bannable.

**Comment by AkadenTK** [comment]
1. //hp tavnazia 1
2. Nope. Thankfully, SE made it so that if the HP (or whatever other system) is not unlocked, even if you send the correct packets to go there, you'll just get locked in the menu with a black screen.
