### ISSUE TITLE
Eastern Adoulin Home Point 1

### ISSUE THREAD

**Issue by Buffylvr** [AkadenTK/superwarp#43]
If you are at Eastern Adoulin HP #1, and do //hp eastern 2 it says you are already at HP 2.

**Comment by MrKayDu** [comment]
Seems like Western Adoulin also has the same issue, trying to waypoint to Western Moghouse from the Auction House stats that you're already at the Moghouse waypoint.

**Comment by eaglejs** [comment]
I'm looking into this, I noticed after this update, a lot of zones warp id's incremented by 1. The original maintainer doesn't play anymore, so I'm going to hope that he/she will see this, see my Pull Request to fix this.

Right now, All of Escha zones warp ID's went up by `1`, I'll take a look at Adoulin, let me know here if you see others.

**Comment by eaglejs** [comment]
oh! Looks like it was already updated! nice!
