### ISSUE TITLE
Already at homepoint issue

### ISSUE THREAD

**Issue by Andrew978** [AkadenTK/superwarp#46]
When I am at Western Adoulin HP1 and try to warp to Western Adoulin 2 it says i'm already at Adoulin 2 but i'm still at 1. If I try to warp from a different zone to adoulin 2 it works correctly, but if i try to go from adoulin1 to adoulin2 it says i'm already at that HP. Can someone help me fix this please?

**Comment by eaglejs** [comment]
This should be fixed now in the latest code.
