### ISSUE TITLE
Can this work on private servers? 

### ISSUE THREAD

**Issue by ShoppyCodes** [AkadenTK/superwarp#48]
Seems this doesn't work on private servers, is it possible to make it work or is it impossible due to the nature of private servers?

Looks like it tries to and then times out: "Timed out waiting for response from the menu. Retrying..." notification.

**Comment by AkadenTK** [comment]
I don't plan on implementing anything for private servers. If somebody does implement a private server version or an option to use private server values and wants to merge it, I will accept a pull request (assuming it doesn't break retail and is well implemented :) ).
