### ISSUE TITLE
HP teleport  could not find zone

### ISSUE THREAD

**Issue by Chevalier501** [AkadenTK/superwarp#5]
I can use auto-translate to complete zone names for teleporting. I'm not sure if this was something by design but it makes typing zones quick and easy. The only zone I've come across so far where it does not work and it gives back a "could not find zone ?'? error" is Kamihr drifts

**Comment by AkadenTK** [comment]
Yes, and I'm actually totally unsure why this is. Superwarp uses windower's own function to strip out the autotranslate icons, but what comes back from Kamihr Drifts isn't text. This should be reported to Windower I think.
