### ISSUE TITLE
Aminon bitzer going down.

### ISSUE THREAD

**Issue by Wickert99** [AkadenTK/superwarp#54]
Hey, love the Sortie enhancement!

Found a bug with Aminon Bitzer using //so all port to go down locked all my guys up. It locked them up the rest of the run and i couldnt cancel etc.

Thank you!

**Comment by AkadenTK** [comment]
Should be resolved after latest update (1.0). Thanks @staticvoid0!

**Comment by Wickert99** [comment]
Just updated and ran sortie. Was so smooth! Was cruising through aita>gartell> then otw to Triboulex and then it started to time out other toons :( so i resorted to manual use. Then doing upstairs "//so all port" just would not send my alts up and down the rest of run :( but the char i used the //so all port command on worked every time. So sorry if i'm bugging i'm just so keen for this to work!

Thank you very much again!
