### ISSUE TITLE
H casket popped on D-side

### ISSUE THREAD

**Issue by Zattano-XI** [AkadenTK/superwarp#60]
H Casket popped on D side after using //so port to move to Floor H. Was going to report it on official forum, but quickly realized it was most likely due to SW. Sidenote: We did not get galli or items from the H casket when popping it in D, most likely due to it being H casket...

Screenshot confirms via mini-map, party member did not capture the bitzer in the image.

![image](https://github.com/user-attachments/assets/a03e5fe8-3d1c-4715-a475-36004c163f59)

**Comment by staticvoid0** [comment]
yeah this has been addressed in the latest pull request, this wasn't so much a bug of the sortie.lua as much as it was just a natural side-effect of using superwarp to spawn this chest, however i accounted for it and it shouldn't be able to happen anymore after merging this latest pull request. I feel these maps should be well polished off now too btw. (Odyssey and Sortie)

**Comment by AkadenTK** [comment]
PR is merged. @Zattano-XI, will you grab latest and make sure it resolves your issue? :)

**Comment by Zattano-XI** [comment]
Tested last night, no issues! Great work!
