### ISSUE TITLE
Ran 2 sorties yesterday. got stuck inside and before boss on 2 different characters. 2 different bosses.

### ISSUE THREAD

**Issue by Avalik09** [AkadenTK/superwarp#62]
im not sure if another addon is conflicting like quicktrade, trade, tradenpc, or something but i've had 2 characters get stuck at bitzer to enter boss arena and trying to exit as well. one got stuck trying to enter C boss. and one got stuck trying to exit degei. logging out doesnt fix it neither does closing the client completely and relogging. no im not using tako or anything like that.

**Comment by Avalik09** [comment]
i'm not sure if it has anything to do with silmaril's warps being available.. i have them from default cause i 7 box but i wasn't using them. i was just using superwarp. i do know from the past if you had tako open while using mirror on bitzers it would do the same thing that happened to me. i can run debugging for superwarp and post a SS but kinda scared to get stuck again lol.

**Comment by AkadenTK** [comment]
I do not intend to resolve issues that conflict with automation tools.

**Comment by Avalik09** [comment]
um ok fuck you too faggot. wickert uses the same shit.
