### ISSUE TITLE
Suggestion: HP to SG and S to HP warp

### ISSUE THREAD

**Issue by SvenBent** [AkadenTK/superwarp#64]
At the SG in tavnazia, the HP and SG are so close you don't have to move between them to use both.

It would be nice to have a settings that would use that as middle stop if you use a //hp command near a SG or vise versa.

**Comment by AkadenTK** [comment]
No. Superwarp is and always will be exclusively a tool for using the various warp systems in the game (and related functionality) in the exact way that the game allows through the menu system. The only difference is convenience and speed.

**Comment by SvenBent** [comment]
I agree.
I don't think i explained myself well as I don't see a conflict in the 2 stated goals.

Right now let says im in mhaura and want to go to the survival guide in cape terrigan
Ill do //hp tavnazia safehold;wait 9;sg cape terrigan
this will warp my from the HP in mhaura to the  HP in tavnazia. wait 9 secs for the map to load and then warp me from the SG in tavnazia to the SG in cape terrigan.
This is currently possible since HP1 in Tavnazia is right next to the SG.

However it is a bit of a lot to type. So instead if im standing at hthe HP in mhaura and type //sg cape terrigan.
addon detects there is no SG anywhere near me (50 yalms detection area i believe). then do the smae as above. take me to tavnazia via the hp in front of me and then use the sg to cape terrigan.

Nothing is something you cant already do with the menu system.. its soly possible because of the close proximity of HP and SG in tavnazia.

**Comment by AkadenTK** [comment]
I understand now. I still don't agree that it should be a feature of Superwarp. Mostly for the complexity-to-benefit ratio. First, to time the teleport such that a packet will be sent just at the right time after the first warp ends is rough. It's certainly not impossible, but I doubt that it would be stable, thus lowering the quality of the addon as a whole. And more than likely causing more frustration than it solves.
I went through a similar thought process when the zone matching algorithm changed. It added more instability to the addon, BUT, it also solved a lot more problems than it caused. And in the end, it was tweaked enough to minimize its complexity-to-benefit ratio. This, I don't think does that.
